kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: digital-ocean-namespace
  name: tiller-manager
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
