kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller
  namespace: digital-ocean-namespace
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: digital-ocean-namespace
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
